// src/ui/App.tsx
import type { JSX, Resource } from "solid-js";
import { createEffect, createResource, createSignal, For, Show } from "solid-js";
import Epub from "~/lib/epub";
import { ContentId, Partition } from "~/lib/translator";
import { CONTENT_ID_ATTRIBUTE, createPreviewDocument } from "./converter";

export default function App() {
    const [file, setFile] = createSignal<File>();
    const [epub] = createResource(file, Epub.from);

    return (
        <div class="flex h-screen flex-col">
            <Show when={epub.loading}>
                <progress class="progress m-0 w-full" />
            </Show>
            <Show when={epub.error}>
                <div class="alert alert-error">
                    {epub.error instanceof Error ? epub.error.message : JSON.stringify(epub.error)}
                </div>
            </Show>
            <Show when={epub()}>{(epub) => <Viewer epub={epub()} />}</Show>
            <Uploader onChange={setFile} />
        </div>
    );
}

function Uploader(props: { onChange: (file: File | undefined) => void }) {
    return (
        <label class="btn btn-primary">
            <input
                type="file"
                accept="application/epub+zip"
                hidden
                class="input input-lg"
                onChange={(event) => props.onChange(event.target.files?.[0] ?? undefined)}
            />
            Upload EPUB File
        </label>
    );
}

function Viewer(props: { epub: Epub }) {
    const [spineIndex, setSpineIndex] = createSignal(0);
    const [previewContent, actions] = createResource<string, number>(spineIndex, (spineIndex) =>
        createPreviewDocument(props.epub, spineIndex),
    );

    createEffect(() => {
        props.epub;
        setSpineIndex(0);
        actions.refetch();
    });

    return (
        <div class="flex flex-1 overflow-y-auto">
            <ViewerNavigation
                spine={props.epub.spine}
                index={spineIndex()}
                onNavigate={setSpineIndex}
            />
            <ViewerPreview content={previewContent} />
        </div>
    );
}

function ViewerNavigation(props: {
    index: number;
    spine: readonly string[];
    onNavigate: (index: number) => void;
}) {
    return (
        <nav class="h-full min-w-fit overflow-y-auto text-xs">
            <ul class="list m-2">
                <For each={props.spine}>
                    {(path, index) => (
                        <li>
                            <button
                                type="button"
                                class="w-full link p-0.5 text-justify link-hover"
                                classList={{ "link-accent": index() === props.index }}
                                onClick={() => props.onNavigate(index())}
                            >
                                {path}
                            </button>
                        </li>
                    )}
                </For>
            </ul>
        </nav>
    );
}

function ViewerPreview(props: { content: Resource<string> }) {
    const handleFrameLoad: JSX.EventHandler<HTMLIFrameElement, Event> = (evt) => {
        const contentDocument = evt.currentTarget.contentDocument!;
        contentDocument.addEventListener("selectionchange", function () {
            const selection = this.getSelection();
            if (selection?.rangeCount) {
                const [partition, range] = makePartitionFromRange(selection.getRangeAt(0));
                console.log(partition, range);
            }
        });
    };

    return (
        <main class="h-full flex-1">
            <Show when={props.content.error}>
                <div class="alert alert-error">
                    {props.content.error instanceof Error
                        ? props.content.error.message
                        : JSON.stringify(props.content.error)}
                </div>
            </Show>
            <Show
                when={props.content()}
                fallback={
                    <div class="flex h-full w-full items-center justify-center">
                        <div class="loading loading-spinner" />
                    </div>
                }
            >
                <iframe
                    title="EPUB Viewer"
                    srcdoc={props.content()}
                    class="h-full w-full"
                    sandbox="allow-same-origin allow-scripts"
                    onLoad={handleFrameLoad}
                />
            </Show>
        </main>
    );
}

function makePartitionFromRange(range: Range): [Partition, Range] {
    const { startContainer, endContainer, commonAncestorContainer } = range;
    const startElement = closestAncestorWithContentId(startContainer);
    const endElement = closestAncestorWithContentId(endContainer);
    const commonAncestorElement = closestAncestorWithContentId(commonAncestorContainer);

    let start: Node, end: Node, size: number;
    if (startElement === commonAncestorElement || endElement === commonAncestorElement) {
        [start, end, size] = [commonAncestorElement, commonAncestorElement, 1];
    } else {
        let [s, e] = [startElement, endElement] as [Node, Node];
        while (s.parentNode !== commonAncestorElement) s = s.parentNode!;
        while (e.parentNode !== commonAncestorElement) e = e.parentNode!;
        [start, end, size] = [s, e, 1];
        while (s !== e && size++) s = s.nextSibling!;
    }

    const offset = ContentId.parse((start as HTMLElement).getAttribute(CONTENT_ID_ATTRIBUTE)!);

    const partitionRange = new Range();
    partitionRange.setStartBefore(start);
    partitionRange.setEndAfter(end);

    return [new Partition(offset, size), partitionRange];
}

function closestAncestorWithContentId(node: Node): Element {
    while (
        node.nodeType !== Node.ELEMENT_NODE ||
        (node as Element).getAttribute(CONTENT_ID_ATTRIBUTE) == null
    ) {
        if (!node.parentNode) throw new Error("Cannot find ancestor with content ID");
        node = node.parentNode;
    }
    return node as Element;
}

// src/app.tsx
import cn from "classnames";
import { type ReactEventHandler, useEffect, useState } from "react";
import Epub from "~/lib/epub";
import { usePrevious, usePromise } from "~/utils/hooks";

export default function App() {
    const [epubPromise, setEpubPromise] = useState<Promise<Epub | null>>(Promise.resolve(null));
    const [epub, error, loading] = usePromise(epubPromise);

    const handleUpload = (file: File | null) => {
        setEpubPromise(file ? Epub.from(file) : Promise.resolve(null));
    };

    return (
        <div className="h-screen flex flex-col">
            {loading ? <progress className="progress w-full m-0" /> : null}
            {error ? (
                <div className="alert alert-error">
                    {error instanceof Error ? error.message : JSON.stringify(error)}
                </div>
            ) : null}
            {epub ? <Viewer epub={epub} /> : null}
            <Uploader onChange={handleUpload} />
        </div>
    );
}

function Uploader(props: { onChange: (file: File | null) => void }) {
    return (
        <label className="btn btn-primary">
            <input
                type="file"
                accept="application/epub+zip"
                hidden
                className="input input-lg"
                onChange={(event) => props.onChange(event.target.files?.[0] ?? null)}
            />
            Upload EPUB File
        </label>
    );
}

function Viewer(props: { epub: Epub }) {
    const prevEpub = usePrevious(props.epub);
    const [index, setIndex] = useState(0);
    const [contentUrl, setContentUrl] = useState<Promise<string>>(() =>
        props.epub.getContentVirtualUrl(index),
    );

    useEffect(() => {
        if (props.epub === prevEpub) {
            setContentUrl(props.epub.getContentVirtualUrl(index));
        } else {
            setIndex(0);
            setContentUrl(props.epub.getContentVirtualUrl(0));
        }
    }, [props.epub, index]);

    return (
        <div className="flex flex-1 overflow-y-auto">
            <ViewerNavigation index={index} spine={props.epub.spine} onNavigate={setIndex} />
            <ViewerFrame url={contentUrl} />
        </div>
    );
}

function ViewerNavigation(props: {
    index: number;
    spine: readonly string[];
    onNavigate: (index: number) => void;
}) {
    return (
        <nav className="text-xs min-w-fit h-full overflow-y-auto">
            <ul className="list m-2">
                {props.spine.map((path, index) => (
                    <li key={path}>
                        <button
                            type="button"
                            className={cn(
                                "w-full p-0.5 text-justify link link-hover",
                                index === props.index ? "link-accent" : null,
                            )}
                            onClick={() => props.onNavigate(index)}
                        >
                            {path}
                        </button>
                    </li>
                ))}
            </ul>
        </nav>
    );
}

function ViewerFrame(props: { url: Promise<string> }) {
    const [url, error, loading] = usePromise(props.url);

    const handleFrameLoad: ReactEventHandler<HTMLIFrameElement> = (evt) => {
        const contentDocument = evt.currentTarget.contentDocument!;
        contentDocument.addEventListener("selectionchange", handleContentSelectionChange);
    };

    return (
        <main className="flex-1 h-full">
            {loading ? (
                <div className="flex items-center justify-center w-full h-full">
                    <div className="loading loading-spinner" />
                </div>
            ) : error ? (
                <div className="alert alert-error">
                    {error instanceof Error ? error.message : JSON.stringify(error)}
                </div>
            ) : (
                <iframe
                    title="EPUB Viewer"
                    src={url}
                    className="w-full h-full"
                    onLoad={handleFrameLoad}
                />
            )}
        </main>
    );
}

function handleContentSelectionChange(this: Document) {
    const selection = this.getSelection();
    if (!selection || selection.rangeCount !== 1) return;

    const range = selection.getRangeAt(0);
    const { startContainer, endContainer, commonAncestorContainer } = range;

    let offset: Node, size: number;
    if (startContainer === commonAncestorContainer || endContainer === commonAncestorContainer) {
        [offset, size] = [commonAncestorContainer, 1];
    } else {
        let [s, e] = [startContainer, endContainer];
        while (s.parentNode !== commonAncestorContainer) s = s.parentNode!;
        while (e.parentNode !== commonAncestorContainer) e = e.parentNode!;
        [offset, size] = [s, 1];
        while (s !== e && size++) s = s.nextSibling!;
    }

    console.log(offset, size);
}
